name: datacollector-ci

on:
  push:
    branches:
      - master
    # paths:
    #   - "cctv-mlops-practice/src/data/data_collect/**"
      
jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: 183.105.120.175:2224
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: check dir
        run : |
          echo `pwd`
      -
        name: change dir
        run : |
          cd src/data/data_collect
      -
        name: check dir2
        run : |
          echo `pwd`
      -
        name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/data/data_collect/
          #push: true
          tags: |
            183.105.120.175:2224/data-collecting:latest
          load: true
      -
        name: Push docker image on Nexus repository
        run: |
          docker push 183.105.120.175:2224/data-collecting:latest
      -
        name: Notify Result
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          username: 윤병관
          channel: '#alarm'
        if: always()
